version: "3"
services:
  mongodb:
    image: 'mongo:4.4.6'
    container_name: mongodb
    hostname: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - genbook-network-internal
    volumes:
      - mongodb-data:/data/db

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - genbook-network-internal

  mysql:
    image: 'mysql:8.0.25'
    container_name: mysql
    hostname: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    networks:
      - genbook-network-internal
    volumes:
        - mysql-data:/var/lib/mysql
  neo4j:
    image: 'neo4j:4.3.1'
    container_name: neo4j
    hostname: neo4j
    ports:
      - '7687:7687'
      - '7474:7474'
      - '7473:7473'
    environment:
      - NEO4J_AUTH=neo4j/12345678
    networks:
      - genbook-network-internal
    volumes:
      - neo4j-data:/data

  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka
    hostname: kafka
    ports:
      - '9094:9094'
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - genbook-network-internal
    volumes:
      - kafka-data:/bitnami/kafka

networks:
  genbook-network-internal:
    driver: bridge
volumes:
    mysql-data:
    neo4j-data:
    kafka-data:
    mongodb-data:
