server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  neo4j:
    uri: http://neo4j:7474
    authentication:
      username: neo4j
      password: 12345678
