server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: 12345678
