name: Build staging

on:
  pull_request:
    branches: [deploy-staging]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup environment
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
        run: |
          echo "Setup environment"
          export BREVO_API_KEY=${{ secrets.BREVO_API_KEY }}
          
      - name: Build all modules
        run: |
          echo "Build all modules"
          mvn clean install -DskipTests

