name: Deploy prod

on:
  workflow_run:
    workflows: [ "Build prod" ]
    types:
      - completed
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run:
          echo "Login to Docker Hub"
          sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Pull Docker Images
        run:
            echo "Pull Docker Images"
#          sudo docker pull trongvinhlam/api-gateway:latest
#          sudo docker pull trongvinhlam/identity-service:latest
#          sudo docker pull trongvinhlam/notification-service:latest
#          sudo docker pull trongvinhlam/post-service:latest
#          sudo docker pull trongvinhlam/profile-service:latest

      - name: Stop and Remove Old Containers
        run: |
          echo "Stop and Remove Old Containers"
#          sudo docker rm -f $(sudo docker ps -aq)

      - name: Start Services using Docker Compose
        run: |
            echo "Start Services using Docker Compose"
#          sudo docker start $(sudo docker ps -aq)
